mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("polls.urls")),
    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views


app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(
        "date published", default=timezone.now, editable=True
    )
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/forms.py
from django import forms

from .models import Question, Choice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ["is_approved"]


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        exclude = ["question"]


ChoiceFormSet = forms.formset_factory(ChoiceForm, extra=3, min_num=1, validate_min=True)

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question
from .forms import QuestionForm, ChoiceFormSet


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"
    ordering = ["-pub_date"]

    def get_queryset(self):
        """Return last 5 recently published questions.

        Returns:
            Question
        """
        return Question.objects.filter(is_approved=True, pub_date__lte=timezone.now())[
            :5
        ]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """Exclude questions that aren't published yet.

        Returns:
            Question
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

    def get_queryset(self):
        """Exclude questions that aren't published yet.

        Returns:
            Question
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


def create(request):
    template_name = "polls/create.html"

    if request.method == "POST":
        question_form = QuestionForm(request.POST or None)
        choices_formset = ChoiceFormSet(request.POST or None)
        if question_form.is_valid() and choices_formset.is_valid():
            question = question_form.save()
            for choice_form in choices_formset:
                if choice_form.has_changed():
                    choice_form.empty_permitted = False
                    choice = choice_form.save(commit=False)
                    choice.question = question
                    choice.save()
            return HttpResponseRedirect(reverse("polls:index"))
    else:
        question_form = QuestionForm()
        choices_formset = ChoiceFormSet()
    context = {"question": question_form, "choices": choices_formset}
    return render(request, "polls/create.html", context)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        context = {"question": question, "error_message": "No selected choice."}
        return render(request, "polls/detail.html", context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

mysite/polls/templates/polls/create.html
<form action="" method="post">
    {% csrf_token %}
    {{ question.as_p }}
    {{ choices.management_form }}
    {% for choice in choices %}
    {{ choice.as_p }}
    {% endfor %}
    <input type="submit">
</form>
{% if question.errors or choices.errors %}
{% endif %}

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}
<p>
    <strong>
        {{ error_message }}
    </strong>
</p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<a href="{% url "polls:create" %}">Create a Poll</a>

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url "polls:detail" question.id %}"> {{ question.question_text }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>Results for {{question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}
    </li>
    {% endfor %}
</ul>

<a href="{% url "polls:detail" question.id %}">Vote Again?</a>

mysite/polls/templates/polls/vote.html
<h1>Voting for {{ question.question_text }}</h1>

{% for choice in question.choice_set.all %}
<button type="type"> {{ choice.choice_text }}</button>
{% endfor %}